"""Build the PG-348 synthetic, loopback-only fixture registry.

The generated pages are inert static challenge surfaces.  They deliberately
model different transport/DOM/redirect/script/state *shapes* without
containing exploit strings, real callbacks, external URLs, credentials, or
business writes.  Raw HTML remains evaluator-only; the registry is metadata
for the abstract surface projector.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = ROOT / "fixtures" / "pg348"
DEFAULT_REGISTRY = DEFAULT_OUTPUT_ROOT / "registry_v1.json"
MECHANISMS = (
    "dom_echo_marker", "dom_attribute_projection", "dom_text_projection", "dom_template_slot",
    "query_shape_branch", "form_shape_branch", "json_shape_branch", "fragment_shape_branch",
    "redirect_shape_branch", "history_shape_branch", "script_event_surface", "script_fetch_shape",
    "script_timer_shape", "script_module_shape", "script_storage_shape", "script_dialog_shape",
    "encoding_percent_chain", "encoding_utf8_chain", "encoding_double_chain", "parameter_role_switch",
    "response_length_bucket", "response_header_shape", "response_content_shape", "failure_parse_shape",
    "failure_block_shape", "belief_step_shape", "state_reset_marker", "negative_control_marker",
)
TEMPLATES = (
    "dashboard", "profile", "search", "settings", "reports", "checkout_preview", "help_center",
    "admin_preview", "mobile_shell", "notification_center",
)
ROLES = ("query_term", "profile_key", "filter_choice", "sort_direction", "note_text", "view_mode", "step_index", "record_cursor")
ENCODINGS = (("identity",), ("query_parameter", "url_percent"), ("form_urlencoded", "utf8"), ("json_object", "utf8"), ("fragment", "utf8"), ("query_parameter", "url_percent", "utf8"))
RESPONSES = ("html_document:200", "html_text:200", "json_shape:200", "html_document:302", "empty_shape:204", "error_shape:400")
REDIRECTS = ("none", "same_origin_fragment", "same_origin_path", "bounded_chain_1", "blocked_external_shape")
SCRIPTS = ("none", "inline_event", "spa_history_pushstate", "module_static", "bounded_fetch_shape", "dialog_shape")


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _page_html(index: int, mechanism: str, template: str, method: str, role: str, encoding: tuple[str, ...], response: str, redirect: str, script: str) -> str:
    # All values are bounded constants generated by this script.  The page has
    # no actual sink, network call, cookie/storage write, or persistent state.
    action = f"/pg348/c/{index:04d}/surface"
    script_block = "" if script == "none" else f'<script type="application/json" data-script-surface="{script}">{{"mode":"abstract","index":{index}}}</script>'
    return f'''<!doctype html>
<html lang="en" data-pg348="synthetic" data-mechanism="{mechanism}" data-template="{template}">
<head><meta charset="utf-8"><meta name="pg348-surface" content="{response}"></head>
<body data-response-shape="{response}" data-redirect-shape="{redirect}" data-state-write="false">
  <main class="surface surface-{template}" data-parameter-role="{role}" data-encoding-chain="{'_then_'.join(encoding)}">
    <h1>Local research surface {index:04d}</h1>
    <form method="{method.lower()}" action="{action}" data-submit-policy="synthetic-preview" data-network="none">
      <label for="field-{index:04d}">{role}</label>
      <input id="field-{index:04d}" name="{role}" value="surface-{index:04d}" autocomplete="off">
      <button type="submit">Preview</button>
    </form>
    <output data-synthetic-oracle="static_projection_only">shape-{index:04d}</output>
  </main>
  {script_block}
</body></html>\n'''


def _write_pages_c(output_root: Path) -> list[dict[str, Any]]:
    pages_dir = output_root / "pages_c"
    pages_dir.mkdir(parents=True, exist_ok=True)
    records: list[dict[str, Any]] = []
    for index in range(1, 281):
        mechanism = MECHANISMS[(index - 1) % len(MECHANISMS)]
        template = TEMPLATES[(index - 1) % len(TEMPLATES)]
        method = "GET" if index % 2 else "POST"
        role = ROLES[(index - 1) % len(ROLES)]
        encoding = ENCODINGS[(index - 1) % len(ENCODINGS)]
        response = RESPONSES[(index - 1) % len(RESPONSES)]
        redirect = REDIRECTS[(index - 1) % len(REDIRECTS)]
        script = SCRIPTS[(index - 1) % len(SCRIPTS)]
        content = _page_html(index, mechanism, template, method, role, encoding, response, redirect, script).encode("utf-8")
        filename = f"pg348-c-{index:04d}.html"
        (pages_dir / filename).write_bytes(content)
        records.append({
            "challenge_id": f"pg348-c-{index:04d}",
            "local_path": f"fixtures/pg348/pages_c/{filename}",
            "mechanism_id": f"pg348.{mechanism}",
            "surface_template_id": f"c_{template}",
            "implementation_group": f"pg348_pages_c_impl_{(index - 1) % 7 + 1}",
            "transport_method": method,
            "parameter_role": role,
            "encoding_chain": list(encoding),
            "response_shape": response,
            "redirect_shape": redirect,
            "script_surface": script,
            "synthetic_oracle_kind": "static_projection_only",
            "source_hash": _sha(content),
            "raw_source_for_evaluator_only": True,
            "training_context_raw": False,
            "loopback_only": True,
            "external_network": False,
            "state_write": False,
            "training_eligible": False,
            "memory_promotion_allowed": False,
            "payload_catalog_promotion_allowed": False,
            "vulnerability_claim_allowed": False,
        })
    return records


def _load_records(path: Path, prefix: str | None = None) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    rows = []
    for original in data.get("records") or []:
        row = dict(original)
        if prefix:
            row["local_path"] = f"{prefix}/{str(row.get('local_path', '')).lstrip('/')}"
        row.setdefault("loopback_only", bool(row.get("localhost_only", True)))
        row.setdefault("external_network", False)
        row.setdefault("state_write", False)
        row.setdefault("training_eligible", False)
        row.setdefault("memory_promotion_allowed", False)
        row.setdefault("payload_catalog_promotion_allowed", False)
        row.setdefault("vulnerability_claim_allowed", False)
        rows.append(row)
    return rows


def build_registry(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, Any]:
    pages_c = _write_pages_c(output_root)
    pages_a = _load_records(output_root / "pages_a" / "manifest_v1.json", "fixtures/pg348/pages_a")
    pages_b = _load_records(output_root / "pages_b" / "fixture_manifest.json", "fixtures/pg348/pages_b")
    records = [*pages_a, *pages_b, *pages_c]
    ids = [str(row["challenge_id"]) for row in records]
    hashes = [str(row["source_hash"]) for row in records]
    mechanisms = sorted({str(row["mechanism_id"]) for row in records})
    templates = sorted({str(row["surface_template_id"]) for row in records})
    methods = {method: sum(row.get("transport_method") == method for row in records) for method in ("GET", "POST")}
    registry = {
        "schema_version": "pg348-500-local-surface-registry-v1",
        "status": "fixture_only_evaluation",
        "registry_status": "pre_registered_candidate_only",
        "sources": [
            {"manifest": "fixtures/pg348/pages_a/manifest_v1.json", "implementation_group": "pg348_pages_a", "raw_source_evaluator_only": True},
            {"manifest": "fixtures/pg348/pages_b/fixture_manifest.json", "implementation_group": "pg348_pages_b", "raw_source_evaluator_only": True},
            {"generator": "scripts/generate_pg348_500_local_fixture_registry.py", "implementation_group": "pg348_pages_c", "raw_source_evaluator_only": True},
        ],
        "counts": {
            "challenge_instances": len(records),
            "unique_challenge_ids": len(set(ids)),
            "unique_source_hashes": len(set(hashes)),
            "mechanism_families": len(mechanisms),
            "surface_templates": len(templates),
            "get_count": methods["GET"],
            "post_count": methods["POST"],
            "transport_variants": len({(row.get("transport_method"), tuple(row.get("encoding_chain") or [])) for row in records}),
            "duplicate_challenge_ids": len(ids) - len(set(ids)),
            "duplicate_source_hashes": len(hashes) - len(set(hashes)),
            "all_urls_loopback_only": all(bool(row.get("loopback_only", row.get("localhost_only", False))) for row in records),
            "external_network_records": sum(bool(row.get("external_network")) for row in records),
            "state_write_records": sum(bool(row.get("state_write")) for row in records),
        },
        "split_plan": {"train_holdout_disjoint_by_mechanism": True, "train_holdout_disjoint_by_template": True, "implementation_holdout_required": True, "raw_source_in_context": False},
        "promotion": {"training_allowed": False, "memory_promotion_allowed": False, "payload_catalog_promotion_allowed": False, "vulnerability_claim_allowed": False},
        "records": records,
    }
    return registry


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the PG-348 500-instance local fixture registry")
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    registry = build_registry(args.output_root)
    if len(registry["records"]) < 500 or registry["counts"]["duplicate_challenge_ids"] or not registry["counts"]["all_urls_loopback_only"]:
        raise SystemExit("PG-348 registry hard check failed")
    args.registry.parent.mkdir(parents=True, exist_ok=True)
    args.registry.write_text(json.dumps(registry, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"status": registry["status"], "counts": registry["counts"], "registry": str(args.registry)}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
